# Generated by Django 3.1.7 on 2021-04-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(default=False, upload_to='media'),
        ),
        migrations.AddField(
            model_name='song',
            name='song_artist',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='song',
            name='song_file',
            field=models.FileField(default=False, upload_to='media'),
        ),
    ]
