# Generated by Django 3.1.7 on 2021-04-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0003_auto_20210401_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
