# Generated by Django 3.1.7 on 2021-04-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicplayer', '0004_auto_20210402_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(default=False, upload_to='media'),
        ),
    ]
